---
all:
  children:
    windows:
      hosts:
        win2019-prueba-01:
          ansible_host: 10.200.254.15
          vmware_vm_name: "WIN2019-PRUEBA-01"
          ambiente: "PRUEBAS"
          servicios_criticos:
            - WinRM
            - W32Time
            - EventLog